name: Bug Report
description: Report a bug or unexpected behavior in GymGurus
title: "[Bug]: "
labels: ["bug", "triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug. Please fill out the sections below to help us investigate and fix the issue.

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: Describe the bug...
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: List the steps to reproduce the behavior.
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: Describe what you expected...
    validations:
      required: true

  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual Behavior
      description: What actually happened?
      placeholder: Describe what actually happened...
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain the problem.
      placeholder: Drag and drop screenshots here...
    validations:
      required: false

  - type: dropdown
    id: area
    attributes:
      label: Affected Area
      description: Which part of the application is affected?
      options:
        - Dashboard
        - Workout Logging
        - Workout Plans
        - Client Management
        - Calculators (BMI/1RM/Strength Standards)
        - AI Features
        - Authentication / Login
        - Onboarding
        - Landing Page
        - Payments / Stripe
        - API / Backend
        - Other
    validations:
      required: true

  - type: dropdown
    id: severity
    attributes:
      label: Severity
      description: How severe is this bug?
      options:
        - Critical - Application crash or data loss
        - High - Major feature broken, no workaround
        - Medium - Feature partially broken, workaround exists
        - Low - Minor issue, cosmetic or edge case
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Provide details about your environment.
      placeholder: |
        - OS: [e.g., Windows 11, macOS 14, Ubuntu 22.04]
        - Browser: [e.g., Chrome 120, Firefox 121, Safari 17]
        - Node.js version: [e.g., 20.10.0]
        - Screen size: [e.g., Desktop 1920x1080, Mobile 390x844]
    validations:
      required: false

  - type: textarea
    id: logs
    attributes:
      label: Console Logs / Error Output
      description: Paste any relevant console logs or error messages.
      render: shell
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Any other context about the problem.
      placeholder: Add any other context here...
    validations:
      required: false
