name: Feature Request
description: Suggest a new feature or improvement for GymGurus
title: "[Feature]: "
labels: ["enhancement"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Please provide as much detail as possible so we can evaluate and prioritize it.

  - type: textarea
    id: summary
    attributes:
      label: Feature Summary
      description: A brief summary of the feature you'd like to see.
      placeholder: Describe the feature in one or two sentences...
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem or Motivation
      description: What problem does this feature solve? Why is it needed?
      placeholder: |
        Is your feature request related to a problem? Describe it here.
        Example: "I'm always frustrated when..."
    validations:
      required: true

  - type: textarea
    id: proposed-solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like to see implemented.
      placeholder: Describe your ideal solution...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered any alternative solutions or workarounds?
      placeholder: Describe any alternatives you've considered...
    validations:
      required: false

  - type: dropdown
    id: area
    attributes:
      label: Feature Area
      description: Which part of the application does this feature relate to?
      options:
        - Dashboard
        - Workout Logging
        - Workout Plans
        - Client Management
        - Calculators (BMI/1RM/Strength Standards)
        - AI Features
        - Authentication / Login
        - Onboarding
        - Landing Page
        - Payments / Stripe
        - Gamification / Achievements
        - Analytics / Reporting
        - API / Backend
        - Performance
        - Accessibility
        - Mobile Experience
        - Other
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Nice to have
        - Important - would significantly improve my experience
        - Critical - blocking my use of the platform
    validations:
      required: true

  - type: textarea
    id: mockups
    attributes:
      label: Mockups or Examples
      description: If applicable, add mockups, wireframes, or links to similar features in other products.
      placeholder: Drag and drop images or paste links here...
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Any other context, details, or references relevant to this feature request.
      placeholder: Add any other context here...
    validations:
      required: false

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      description: Would you be willing to help implement this feature?
      options:
        - label: I would be willing to submit a PR for this feature
          required: false
