/**
 * Exercise Library Seed
 * Run: npm run seed:exercises
 * Idempotent — only seeds if the exercises table is empty.
 */
import { neon } from '@neondatabase/serverless';
import { drizzle } from 'drizzle-orm/neon-http';
import { exercises } from '../../shared/schema';
import { sql } from 'drizzle-orm';

const db = drizzle(neon(process.env.DATABASE_URL!));

interface ExerciseSeed {
  name: string;
  description: string;
  category: string;
  difficulty: 'beginner' | 'intermediate' | 'advanced';
  muscleGroups: string[];
  equipment: string[];
  instructions: string[];
  youtubeUrl?: string;
  defaultSets?: number;
  defaultReps?: number;
}

const EXERCISES: ExerciseSeed[] = [
  // ─── CHEST (15) ───────────────────────────────────────────────────────────
  {
    name: 'Barbell Bench Press',
    description:
      'The king of chest exercises. Lying flat on a bench, press a barbell from chest height to full arm extension.',
    category: 'Chest',
    difficulty: 'intermediate',
    muscleGroups: ['Chest', 'Triceps', 'Front Deltoids'],
    equipment: ['Barbell', 'Bench', 'Rack'],
    instructions: [
      'Lie flat on the bench with eyes under the bar.',
      'Grip the bar slightly wider than shoulder-width.',
      'Unrack the bar and lower it to your chest slowly.',
      'Press the bar back up to full arm extension.',
      'Keep your feet flat and back slightly arched.',
    ],
    youtubeUrl: 'https://www.youtube.com/watch?v=rT7DgCr-3pg',
    defaultSets: 4,
    defaultReps: 8,
  },
  {
    name: 'Incline Dumbbell Press',
    description: 'Upper-chest focused press performed on a 30–45° incline bench with dumbbells.',
    category: 'Chest',
    difficulty: 'intermediate',
    muscleGroups: ['Upper Chest', 'Triceps', 'Front Deltoids'],
    equipment: ['Dumbbells', 'Incline Bench'],
    instructions: [
      'Set bench to 30–45° incline.',
      'Hold dumbbells at shoulder width, palms facing forward.',
      'Press dumbbells upward until arms are fully extended.',
      'Lower slowly back to chest level.',
      'Keep core tight and feet flat on the floor.',
    ],
    youtubeUrl: 'https://www.youtube.com/watch?v=8iPEnn-ltC8',
    defaultSets: 3,
    defaultReps: 10,
  },
  {
    name: 'Cable Fly',
    description:
      'Chest isolation movement using cables for constant tension throughout the range of motion.',
    category: 'Chest',
    difficulty: 'intermediate',
    muscleGroups: ['Chest', 'Front Deltoids'],
    equipment: ['Cable Machine'],
    instructions: [
      'Set cables to shoulder height and stand in the middle.',
      'Grab a handle in each hand and step forward.',
      'With a slight bend in the elbows, bring hands together in front of chest.',
      'Slowly return to starting position maintaining tension.',
      'Keep chest up and core tight throughout.',
    ],
    youtubeUrl: 'https://www.youtube.com/watch?v=Iwe6AmxVf7o',
    defaultSets: 3,
    defaultReps: 12,
  },
  {
    name: 'Push-Up',
    description: 'Fundamental bodyweight chest exercise requiring no equipment.',
    category: 'Chest',
    difficulty: 'beginner',
    muscleGroups: ['Chest', 'Triceps', 'Front Deltoids', 'Core'],
    equipment: [],
    instructions: [
      'Start in high plank position, hands slightly wider than shoulders.',
      'Lower your chest to the floor, keeping body straight.',
      'Push through palms to return to starting position.',
      'Keep core engaged and hips level throughout.',
    ],
    youtubeUrl: 'https://www.youtube.com/watch?v=IODxDxX7oi4',
    defaultSets: 3,
    defaultReps: 15,
  },
  {
    name: 'Chest Dip',
    description:
      'Compound lower-chest exercise performed on parallel bars, leaning forward to emphasize chest.',
    category: 'Chest',
    difficulty: 'intermediate',
    muscleGroups: ['Lower Chest', 'Triceps', 'Front Deltoids'],
    equipment: ['Parallel Bars'],
    instructions: [
      'Mount parallel bars and straighten arms.',
      'Lean forward slightly (about 30°) to shift emphasis to chest.',
      'Lower yourself by bending elbows until you feel a chest stretch.',
      'Push back up to starting position.',
      'Add weight with a belt when bodyweight becomes easy.',
    ],
    youtubeUrl: 'https://www.youtube.com/watch?v=2z8JmcrW-As',
    defaultSets: 3,
    defaultReps: 10,
  },
  {
    name: 'Pec Deck Machine',
    description: 'Machine fly variation for chest isolation with guided range of motion.',
    category: 'Chest',
    difficulty: 'beginner',
    muscleGroups: ['Chest', 'Front Deltoids'],
    equipment: ['Pec Deck Machine'],
    instructions: [
      'Adjust seat height so handles align with mid-chest.',
      'Place forearms on pads and grasp handles.',
      'Bring arms together in front of chest, squeezing pecs.',
      'Slowly return to starting position.',
    ],
    youtubeUrl: 'https://www.youtube.com/watch?v=Z57CtFmRMxA',
    defaultSets: 3,
    defaultReps: 15,
  },
  {
    name: 'Decline Barbell Press',
    description: 'Targets the lower chest by pressing on a decline bench.',
    category: 'Chest',
    difficulty: 'intermediate',
    muscleGroups: ['Lower Chest', 'Triceps'],
    equipment: ['Barbell', 'Decline Bench'],
    instructions: [
      'Set bench to 15–30° decline and secure ankles.',
      'Grip bar slightly wider than shoulder-width.',
      'Lower bar to lower chest, keeping elbows at 45°.',
      'Press bar back to full extension.',
    ],
    youtubeUrl: 'https://www.youtube.com/watch?v=LfyQBUKR8SE',
    defaultSets: 3,
    defaultReps: 10,
  },
  {
    name: 'Dumbbell Fly',
    description:
      'Chest isolation exercise using dumbbells to stretch and contract the pectoral muscles.',
    category: 'Chest',
    difficulty: 'beginner',
    muscleGroups: ['Chest', 'Front Deltoids'],
    equipment: ['Dumbbells', 'Bench'],
    instructions: [
      'Lie flat on bench, dumbbells directly above chest.',
      'Lower arms in a wide arc keeping a slight bend in elbows.',
      'Stretch until you feel a pull in the chest.',
      'Bring dumbbells back together above chest, squeezing pecs.',
    ],
    youtubeUrl: 'https://www.youtube.com/watch?v=eozdVDA78K0',
    defaultSets: 3,
    defaultReps: 12,
  },
  {
    name: 'Landmine Press',
    description:
      'Unilateral press using a barbell anchored at one end. Great for shoulder-friendly chest work.',
    category: 'Chest',
    difficulty: 'intermediate',
    muscleGroups: ['Chest', 'Triceps', 'Front Deltoids'],
    equipment: ['Barbell', 'Landmine Attachment'],
    instructions: [
      'Anchor one end of a barbell in a corner or landmine.',
      'Hold the other end at chest height with one hand.',
      'Press the bar upward and forward until arm extends.',
      'Return slowly and repeat on both sides.',
    ],
    youtubeUrl: 'https://www.youtube.com/watch?v=P9A0l7Kucuc',
    defaultSets: 3,
    defaultReps: 10,
  },
  {
    name: 'Diamond Push-Up',
    description:
      'Push-up variation with a narrow, diamond-shaped hand position that shifts emphasis to the inner chest and triceps.',
    category: 'Chest',
    difficulty: 'intermediate',
    muscleGroups: ['Inner Chest', 'Triceps'],
    equipment: [],
    instructions: [
      'Form a diamond with thumbs and index fingers on the floor.',
      'Lower chest to hands, keeping elbows tucked.',
      'Press back to start.',
    ],
    youtubeUrl: 'https://www.youtube.com/watch?v=J0DnG1_S92I',
    defaultSets: 3,
    defaultReps: 12,
  },
  {
    name: 'Smith Machine Bench Press',
    description: 'Guided barbell bench press for beginners or when training without a spotter.',
    category: 'Chest',
    difficulty: 'beginner',
    muscleGroups: ['Chest', 'Triceps', 'Front Deltoids'],
    equipment: ['Smith Machine', 'Bench'],
    instructions: [
      'Set bar at appropriate height and lie on bench.',
      'Unrack the bar by rotating wrists.',
      'Lower bar to chest and press back to full extension.',
      'Rerack by rotating wrists into safety hooks.',
    ],
    youtubeUrl: 'https://www.youtube.com/watch?v=jPLdzuHckI8',
    defaultSets: 3,
    defaultReps: 10,
  },
  {
    name: 'Wide-Grip Push-Up',
    description: 'Push-up with hands placed wider than shoulders to increase chest activation.',
    category: 'Chest',
    difficulty: 'beginner',
    muscleGroups: ['Outer Chest', 'Front Deltoids', 'Triceps'],
    equipment: [],
    instructions: [
      'Place hands wider than shoulder-width apart.',
      'Keep body in straight line from head to heels.',
      'Lower chest toward floor, then press back up.',
    ],
    youtubeUrl: 'https://www.youtube.com/watch?v=2_Cbiy2YDyo',
    defaultSets: 3,
    defaultReps: 15,
  },
  {
    name: 'Low Cable Fly',
    description:
      'Cable fly with cables set low, targeting the upper chest through a different angle.',
    category: 'Chest',
    difficulty: 'intermediate',
    muscleGroups: ['Upper Chest', 'Front Deltoids'],
    equipment: ['Cable Machine'],
    instructions: [
      'Set cables at the lowest position.',
      'Stand in the middle and grip handles.',
      'Bring hands together above chest level in an arc.',
      'Slowly lower back to starting position.',
    ],
    youtubeUrl: 'https://www.youtube.com/watch?v=BDE_GnGG2JQ',
    defaultSets: 3,
    defaultReps: 12,
  },
  {
    name: 'Incline Barbell Press',
    description: 'Barbell press on a 30–45° incline to target the upper chest.',
    category: 'Chest',
    difficulty: 'intermediate',
    muscleGroups: ['Upper Chest', 'Triceps', 'Front Deltoids'],
    equipment: ['Barbell', 'Incline Bench', 'Rack'],
    instructions: [
      'Set incline bench to 30–45°.',
      'Grip bar slightly wider than shoulder-width.',
      'Lower bar to upper chest and press back up.',
    ],
    youtubeUrl: 'https://www.youtube.com/watch?v=jPLdzuHckI8',
    defaultSets: 4,
    defaultReps: 8,
  },
  {
    name: 'Chest Press Machine',
    description: 'Machine-based chest press for safe, isolated chest development.',
    category: 'Chest',
    difficulty: 'beginner',
    muscleGroups: ['Chest', 'Triceps'],
    equipment: ['Chest Press Machine'],
    instructions: [
      'Adjust seat so handles align with mid-chest.',
      'Grip handles and press forward until arms extend.',
      'Return slowly to starting position.',
    ],
    youtubeUrl: 'https://www.youtube.com/watch?v=xUm0BiZCe_s',
    defaultSets: 3,
    defaultReps: 12,
  },

  // ─── BACK (15) ────────────────────────────────────────────────────────────
  {
    name: 'Conventional Deadlift',
    description: 'The foundational compound lift working the entire posterior chain.',
    category: 'Back',
    difficulty: 'advanced',
    muscleGroups: ['Lower Back', 'Glutes', 'Hamstrings', 'Traps', 'Lats'],
    equipment: ['Barbell'],
    instructions: [
      'Stand with feet hip-width apart, bar over mid-foot.',
      'Hinge at hips and grip bar just outside legs.',
      'Flatten your back and create tension in lats.',
      'Drive through the floor, pushing hips forward as bar passes knees.',
      'Stand tall at top, then hinge back to lower.',
    ],
    youtubeUrl: 'https://www.youtube.com/watch?v=op9kVnSso6Q',
    defaultSets: 4,
    defaultReps: 5,
  },
  {
    name: 'Pull-Up',
    description: 'The gold standard of back exercises using only bodyweight and a bar.',
    category: 'Back',
    difficulty: 'intermediate',
    muscleGroups: ['Lats', 'Biceps', 'Rear Deltoids', 'Rhomboids'],
    equipment: ['Pull-Up Bar'],
    instructions: [
      'Hang from bar with overhand grip, slightly wider than shoulders.',
      'Pull chest toward bar by driving elbows down and back.',
      'Go until chin clears the bar.',
      'Lower with control to full hang.',
    ],
    youtubeUrl: 'https://www.youtube.com/watch?v=eGo4IYlbE5g',
    defaultSets: 4,
    defaultReps: 8,
  },
  {
    name: 'Lat Pulldown',
    description: 'Cable machine exercise targeting the lats, mimicking the pull-up movement.',
    category: 'Back',
    difficulty: 'beginner',
    muscleGroups: ['Lats', 'Biceps', 'Rear Deltoids'],
    equipment: ['Cable Machine', 'Lat Bar'],
    instructions: [
      'Sit at lat pulldown machine, lock thighs under pad.',
      'Grip bar wider than shoulders, lean back slightly.',
      'Pull bar to upper chest, driving elbows down.',
      'Squeeze lats at bottom, then extend arms slowly.',
    ],
    youtubeUrl: 'https://www.youtube.com/watch?v=CAwf7n6Luuc',
    defaultSets: 4,
    defaultReps: 10,
  },
  {
    name: 'Seated Cable Row',
    description: 'Cable row targeting mid-back, rhomboids, and lats for thickness.',
    category: 'Back',
    difficulty: 'beginner',
    muscleGroups: ['Mid Back', 'Rhomboids', 'Lats', 'Biceps'],
    equipment: ['Cable Machine', 'Row Handle'],
    instructions: [
      'Sit at row machine with feet on platform, knees slightly bent.',
      'Grip handle and sit upright.',
      'Pull handle to lower abdomen, driving elbows back.',
      'Squeeze shoulder blades together at end position.',
      'Return with control.',
    ],
    youtubeUrl: 'https://www.youtube.com/watch?v=GZbfZ033f74',
    defaultSets: 4,
    defaultReps: 10,
  },
  {
    name: 'Barbell Row',
    description: 'Compound rowing movement for total back thickness and strength.',
    category: 'Back',
    difficulty: 'intermediate',
    muscleGroups: ['Lats', 'Rhomboids', 'Traps', 'Biceps', 'Lower Back'],
    equipment: ['Barbell'],
    instructions: [
      'Hinge forward to about 45°, back flat, core tight.',
      'Grip bar just outside hip width.',
      'Pull bar to lower abdomen, leading with elbows.',
      'Squeeze shoulder blades and lower with control.',
    ],
    youtubeUrl: 'https://www.youtube.com/watch?v=9efgcAjQe7E',
    defaultSets: 4,
    defaultReps: 8,
  },
  {
    name: 'Single-Arm Dumbbell Row',
    description: 'Unilateral rowing exercise for balanced back development.',
    category: 'Back',
    difficulty: 'beginner',
    muscleGroups: ['Lats', 'Rhomboids', 'Rear Deltoids', 'Biceps'],
    equipment: ['Dumbbells', 'Bench'],
    instructions: [
      'Place one knee and hand on bench for support.',
      'Hold dumbbell in opposite hand.',
      'Pull dumbbell to hip, driving elbow back and up.',
      'Lower with control and repeat.',
    ],
    youtubeUrl: 'https://www.youtube.com/watch?v=roCP6wCXPqo',
    defaultSets: 3,
    defaultReps: 12,
  },
  {
    name: 'T-Bar Row',
    description: 'Supported compound rowing movement for mid-back thickness.',
    category: 'Back',
    difficulty: 'intermediate',
    muscleGroups: ['Mid Back', 'Lats', 'Rhomboids', 'Biceps'],
    equipment: ['T-Bar Machine', 'Barbell'],
    instructions: [
      'Stand over the T-bar with feet shoulder-width apart.',
      'Grip handles and hinge forward slightly.',
      'Pull the bar to your lower chest/upper abdomen.',
      'Lower with control.',
    ],
    youtubeUrl: 'https://www.youtube.com/watch?v=j3Igk5nyZE4',
    defaultSets: 4,
    defaultReps: 10,
  },
  {
    name: 'Face Pull',
    description:
      'Cable exercise for rear delts, rhomboids, and external rotators. Great for shoulder health.',
    category: 'Back',
    difficulty: 'beginner',
    muscleGroups: ['Rear Deltoids', 'Rhomboids', 'External Rotators'],
    equipment: ['Cable Machine', 'Rope Attachment'],
    instructions: [
      'Set cable at face height with rope attachment.',
      'Grip rope with thumbs up and step back.',
      'Pull rope to face, elbows flaring high.',
      'Externally rotate at end range, then return.',
    ],
    youtubeUrl: 'https://www.youtube.com/watch?v=rep-qVOkqgk',
    defaultSets: 3,
    defaultReps: 15,
  },
  {
    name: 'Chin-Up',
    description:
      'Underhand grip pull-up that increases bicep involvement while still targeting lats.',
    category: 'Back',
    difficulty: 'intermediate',
    muscleGroups: ['Lats', 'Biceps', 'Lower Traps'],
    equipment: ['Pull-Up Bar'],
    instructions: [
      'Hang from bar with underhand grip, shoulder-width.',
      'Pull chin above bar by driving elbows down.',
      'Lower slowly to full arm extension.',
    ],
    youtubeUrl: 'https://www.youtube.com/watch?v=brhRXlOhsAM',
    defaultSets: 4,
    defaultReps: 8,
  },
  {
    name: 'Rack Pull',
    description:
      'Partial deadlift starting from knee height. Overloads the top portion of the deadlift.',
    category: 'Back',
    difficulty: 'advanced',
    muscleGroups: ['Lower Back', 'Traps', 'Glutes', 'Hamstrings'],
    equipment: ['Barbell', 'Power Rack'],
    instructions: [
      'Set safeties at knee height in power rack.',
      'Grip bar overhand or mixed.',
      'Drive hips forward to lift bar to lockout.',
      'Lower back to pins under control.',
    ],
    youtubeUrl: 'https://www.youtube.com/watch?v=0cxGECdZk_8',
    defaultSets: 3,
    defaultReps: 5,
  },
  {
    name: 'Straight-Arm Pulldown',
    description:
      'Lat isolation exercise keeping arms straight for maximum lat stretch and contraction.',
    category: 'Back',
    difficulty: 'beginner',
    muscleGroups: ['Lats', 'Teres Major'],
    equipment: ['Cable Machine', 'Straight Bar'],
    instructions: [
      'Stand at cable machine, grip bar at eye level.',
      'Keep arms straight with slight elbow bend.',
      'Pull bar down to thighs in an arc.',
      'Return slowly, feeling lats stretch.',
    ],
    youtubeUrl: 'https://www.youtube.com/watch?v=wFKpP_N-mQs',
    defaultSets: 3,
    defaultReps: 12,
  },
  {
    name: 'Inverted Row',
    description: 'Bodyweight row using a barbell in a rack. Great horizontal pull for beginners.',
    category: 'Back',
    difficulty: 'beginner',
    muscleGroups: ['Mid Back', 'Rhomboids', 'Biceps'],
    equipment: ['Barbell', 'Power Rack'],
    instructions: [
      'Set bar at hip height in rack.',
      'Hang underneath with straight body, hands shoulder-width.',
      'Pull chest to bar, squeezing shoulder blades.',
      'Lower with control.',
    ],
    youtubeUrl: 'https://www.youtube.com/watch?v=dvkIaarnf0g',
    defaultSets: 3,
    defaultReps: 12,
  },
  {
    name: 'Pendlay Row',
    description:
      'Strict version of the barbell row — bar starts dead on the floor each rep for maximum power.',
    category: 'Back',
    difficulty: 'advanced',
    muscleGroups: ['Lats', 'Rhomboids', 'Traps', 'Lower Back'],
    equipment: ['Barbell'],
    instructions: [
      'Hinge to parallel with floor, back flat.',
      'Grip bar at hip width.',
      'Explosively row bar to lower chest.',
      'Lower bar completely to floor between reps.',
    ],
    youtubeUrl: 'https://www.youtube.com/watch?v=QbqLPxbhNkk',
    defaultSets: 4,
    defaultReps: 6,
  },
  {
    name: 'Back Extension',
    description: 'Lower back and glute exercise on a hyperextension bench.',
    category: 'Back',
    difficulty: 'beginner',
    muscleGroups: ['Lower Back', 'Glutes', 'Hamstrings'],
    equipment: ['Hyperextension Bench'],
    instructions: [
      'Position hips at the top of the pad, feet secured.',
      'Cross arms on chest or hold weight.',
      'Lower torso toward floor, then extend back to level.',
      'Squeeze glutes at top.',
    ],
    youtubeUrl: 'https://www.youtube.com/watch?v=ph3pddpKzzw',
    defaultSets: 3,
    defaultReps: 15,
  },
  {
    name: 'Wide-Grip Lat Pulldown',
    description: 'Lat pulldown with a wider grip to emphasize outer lat width.',
    category: 'Back',
    difficulty: 'beginner',
    muscleGroups: ['Outer Lats', 'Teres Major', 'Rear Deltoids'],
    equipment: ['Cable Machine', 'Wide Bar'],
    instructions: [
      'Grip bar as wide as comfortable.',
      'Lean back slightly and pull bar to upper chest.',
      'Focus on driving elbows down and back.',
      'Return with control.',
    ],
    youtubeUrl: 'https://www.youtube.com/watch?v=CAwf7n6Luuc',
    defaultSets: 3,
    defaultReps: 12,
  },

  // ─── SHOULDERS (12) ───────────────────────────────────────────────────────
  {
    name: 'Overhead Barbell Press',
    description:
      'The foundational shoulder strength exercise — pressing a barbell overhead from a standing or seated position.',
    category: 'Shoulders',
    difficulty: 'intermediate',
    muscleGroups: ['Front Deltoids', 'Side Deltoids', 'Triceps', 'Traps'],
    equipment: ['Barbell', 'Rack'],
    instructions: [
      'Hold bar at shoulder height, hands just outside shoulders.',
      'Press bar straight overhead to full arm extension.',
      'Lower back to clavicle level with control.',
      'Keep core braced throughout.',
    ],
    youtubeUrl: 'https://www.youtube.com/watch?v=2yjwXTZQDDI',
    defaultSets: 4,
    defaultReps: 8,
  },
  {
    name: 'Dumbbell Lateral Raise',
    description: 'Isolation exercise for the side deltoids to build shoulder width.',
    category: 'Shoulders',
    difficulty: 'beginner',
    muscleGroups: ['Side Deltoids'],
    equipment: ['Dumbbells'],
    instructions: [
      'Stand with dumbbells at sides, palms facing in.',
      'Raise arms to shoulder height with slight bend in elbows.',
      'Lead with pinkies (slight pinky-up rotation).',
      'Lower with control — avoid swinging.',
    ],
    youtubeUrl: 'https://www.youtube.com/watch?v=3VcKaXpzqRo',
    defaultSets: 4,
    defaultReps: 15,
  },
  {
    name: 'Arnold Press',
    description:
      'Rotational dumbbell press invented by Arnold Schwarzenegger that hits all three deltoid heads.',
    category: 'Shoulders',
    difficulty: 'intermediate',
    muscleGroups: ['Front Deltoids', 'Side Deltoids', 'Rear Deltoids', 'Triceps'],
    equipment: ['Dumbbells'],
    instructions: [
      'Start with dumbbells at chin height, palms facing you.',
      'As you press, rotate palms outward.',
      'Press to full extension overhead.',
      'Reverse the rotation as you lower.',
    ],
    youtubeUrl: 'https://www.youtube.com/watch?v=vj2w851ZHRM',
    defaultSets: 3,
    defaultReps: 10,
  },
  {
    name: 'Front Raise',
    description: 'Isolation exercise targeting the front deltoids.',
    category: 'Shoulders',
    difficulty: 'beginner',
    muscleGroups: ['Front Deltoids'],
    equipment: ['Dumbbells'],
    instructions: [
      'Hold dumbbells in front of thighs, palms down.',
      'Raise arms to shoulder height, keeping slight elbow bend.',
      'Lower with control.',
      'Alternate arms or raise both together.',
    ],
    youtubeUrl: 'https://www.youtube.com/watch?v=sOoBfhMoFKQ',
    defaultSets: 3,
    defaultReps: 12,
  },
  {
    name: 'Rear Delt Fly',
    description: 'Bent-over fly for the rear deltoids and upper back.',
    category: 'Shoulders',
    difficulty: 'beginner',
    muscleGroups: ['Rear Deltoids', 'Rhomboids', 'Traps'],
    equipment: ['Dumbbells'],
    instructions: [
      'Hinge forward at hips to about 45°.',
      'Hold dumbbells with palms facing each other.',
      'Raise arms to the sides, squeezing shoulder blades.',
      'Lower slowly to start.',
    ],
    youtubeUrl: 'https://www.youtube.com/watch?v=EA7u4Q_8HQ0',
    defaultSets: 3,
    defaultReps: 15,
  },
  {
    name: 'Dumbbell Shoulder Press',
    description:
      'Seated or standing overhead press with dumbbells for bilateral or independent shoulder development.',
    category: 'Shoulders',
    difficulty: 'beginner',
    muscleGroups: ['Front Deltoids', 'Side Deltoids', 'Triceps'],
    equipment: ['Dumbbells'],
    instructions: [
      'Hold dumbbells at shoulder height, elbows at 90°.',
      'Press both dumbbells overhead to full extension.',
      'Lower back to shoulder height with control.',
    ],
    youtubeUrl: 'https://www.youtube.com/watch?v=qEwKCR5JCog',
    defaultSets: 4,
    defaultReps: 10,
  },
  {
    name: 'Cable Lateral Raise',
    description: 'Single-arm lateral raise with cable for constant tension on the side delt.',
    category: 'Shoulders',
    difficulty: 'beginner',
    muscleGroups: ['Side Deltoids'],
    equipment: ['Cable Machine'],
    instructions: [
      'Set cable to lowest position and stand to the side.',
      'Hold cable handle across body with opposite hand.',
      'Raise arm to shoulder height.',
      'Lower with control and repeat.',
    ],
    youtubeUrl: 'https://www.youtube.com/watch?v=sJdAJLlJEnY',
    defaultSets: 3,
    defaultReps: 15,
  },
  {
    name: 'Upright Row',
    description: 'Compound pulling exercise targeting side deltoids and traps.',
    category: 'Shoulders',
    difficulty: 'intermediate',
    muscleGroups: ['Side Deltoids', 'Traps'],
    equipment: ['Barbell', 'Dumbbells'],
    instructions: [
      'Hold bar or dumbbells at thighs, shoulder-width grip.',
      'Pull up along your body to chin height, leading with elbows.',
      'Keep elbows above wrists at top.',
      'Lower with control.',
    ],
    youtubeUrl: 'https://www.youtube.com/watch?v=amCU-ziHITM',
    defaultSets: 3,
    defaultReps: 12,
  },
  {
    name: 'Band Pull-Apart',
    description:
      'Resistance band exercise for rear delts and external rotators. Excellent for shoulder health.',
    category: 'Shoulders',
    difficulty: 'beginner',
    muscleGroups: ['Rear Deltoids', 'Rhomboids', 'External Rotators'],
    equipment: ['Resistance Band'],
    instructions: [
      'Hold band with both hands at shoulder height, arms extended.',
      'Pull band apart by moving hands to sides.',
      'Squeeze shoulder blades at full stretch.',
      'Return to start.',
    ],
    youtubeUrl: 'https://www.youtube.com/watch?v=TFatbKBwHpE',
    defaultSets: 3,
    defaultReps: 20,
  },
  {
    name: 'Push Press',
    description: 'Overhead press using a slight leg drive to move heavier loads overhead.',
    category: 'Shoulders',
    difficulty: 'intermediate',
    muscleGroups: ['Front Deltoids', 'Side Deltoids', 'Triceps', 'Quads'],
    equipment: ['Barbell'],
    instructions: [
      'Hold bar at shoulder height in a rack position.',
      'Dip knees slightly and drive bar overhead with leg power.',
      'Lock out arms at top.',
      'Lower back to shoulders with control.',
    ],
    youtubeUrl: 'https://www.youtube.com/watch?v=iaBVSJm78ko',
    defaultSets: 4,
    defaultReps: 6,
  },
  {
    name: 'Machine Shoulder Press',
    description: 'Guided overhead press on a machine for safe, isolated shoulder development.',
    category: 'Shoulders',
    difficulty: 'beginner',
    muscleGroups: ['Front Deltoids', 'Side Deltoids', 'Triceps'],
    equipment: ['Shoulder Press Machine'],
    instructions: [
      'Adjust seat so handles are at shoulder height.',
      'Press handles overhead until arms are fully extended.',
      'Lower slowly back to start.',
    ],
    youtubeUrl: 'https://www.youtube.com/watch?v=Wqnal9bnCgQ',
    defaultSets: 3,
    defaultReps: 12,
  },
  {
    name: 'Shrug',
    description: 'Upper trap isolation exercise for neck and trap development.',
    category: 'Shoulders',
    difficulty: 'beginner',
    muscleGroups: ['Upper Traps', 'Neck'],
    equipment: ['Barbell', 'Dumbbells'],
    instructions: [
      'Hold weight in front of thighs.',
      'Elevate shoulders straight up toward ears.',
      'Hold for a second, then lower.',
      'Avoid rolling shoulders.',
    ],
    youtubeUrl: 'https://www.youtube.com/watch?v=cJRVVxmytaM',
    defaultSets: 3,
    defaultReps: 15,
  },

  // ─── ARMS (12) ────────────────────────────────────────────────────────────
  {
    name: 'Barbell Curl',
    description: 'Classic barbell exercise for bilateral bicep development.',
    category: 'Arms',
    difficulty: 'beginner',
    muscleGroups: ['Biceps', 'Forearms'],
    equipment: ['Barbell'],
    instructions: [
      'Stand with bar at hip height, underhand grip.',
      'Curl bar to shoulder height, keeping elbows at sides.',
      'Squeeze biceps at top.',
      'Lower with control.',
    ],
    youtubeUrl: 'https://www.youtube.com/watch?v=kwG2ipFRgfo',
    defaultSets: 4,
    defaultReps: 10,
  },
  {
    name: 'Hammer Curl',
    description: 'Neutral-grip curl targeting biceps and brachialis for arm thickness.',
    category: 'Arms',
    difficulty: 'beginner',
    muscleGroups: ['Biceps', 'Brachialis', 'Forearms'],
    equipment: ['Dumbbells'],
    instructions: [
      'Hold dumbbells with neutral grip (thumbs up).',
      'Curl to shoulder height keeping palms facing each other.',
      'Lower with control.',
    ],
    youtubeUrl: 'https://www.youtube.com/watch?v=TwD-YGVP4Bk',
    defaultSets: 3,
    defaultReps: 12,
  },
  {
    name: 'Tricep Pushdown',
    description: 'Cable isolation exercise for the triceps using a rope or bar attachment.',
    category: 'Arms',
    difficulty: 'beginner',
    muscleGroups: ['Triceps'],
    equipment: ['Cable Machine', 'Rope Attachment'],
    instructions: [
      'Set cable to high position with rope attachment.',
      'Grip rope and keep elbows at sides.',
      'Push rope down and apart until arms fully extend.',
      'Return to 90° with control.',
    ],
    youtubeUrl: 'https://www.youtube.com/watch?v=2-LAMcpzODU',
    defaultSets: 3,
    defaultReps: 12,
  },
  {
    name: 'Skull Crusher',
    description: 'Lying tricep extension with a barbell or EZ bar for mass building.',
    category: 'Arms',
    difficulty: 'intermediate',
    muscleGroups: ['Triceps'],
    equipment: ['Barbell', 'EZ Bar', 'Bench'],
    instructions: [
      'Lie on bench, press bar to full extension above chest.',
      'Lower bar to forehead by bending only at elbows.',
      'Extend back to start.',
      'Keep upper arms vertical and stationary.',
    ],
    youtubeUrl: 'https://www.youtube.com/watch?v=d_KZxkY_0cM',
    defaultSets: 3,
    defaultReps: 10,
  },
  {
    name: 'Concentration Curl',
    description: 'Seated isolation curl for maximum bicep peak.',
    category: 'Arms',
    difficulty: 'beginner',
    muscleGroups: ['Biceps'],
    equipment: ['Dumbbells'],
    instructions: [
      'Sit with one elbow resting on inner thigh.',
      'Curl dumbbell up to shoulder, squeezing hard.',
      'Lower with full control.',
    ],
    youtubeUrl: 'https://www.youtube.com/watch?v=Jvj2wV0vOFU',
    defaultSets: 3,
    defaultReps: 12,
  },
  {
    name: 'Tricep Dip',
    description: 'Bodyweight tricep exercise on a bench or parallel bars.',
    category: 'Arms',
    difficulty: 'beginner',
    muscleGroups: ['Triceps', 'Front Deltoids'],
    equipment: ['Bench', 'Parallel Bars'],
    instructions: [
      'Place hands on bench behind you, feet out.',
      'Lower by bending elbows to 90°.',
      'Push back up to full extension.',
      'Keep torso upright to target triceps.',
    ],
    youtubeUrl: 'https://www.youtube.com/watch?v=6kALZikXxLc',
    defaultSets: 3,
    defaultReps: 15,
  },
  {
    name: 'Cable Curl',
    description: 'Constant-tension bicep curl using a cable machine.',
    category: 'Arms',
    difficulty: 'beginner',
    muscleGroups: ['Biceps'],
    equipment: ['Cable Machine'],
    instructions: [
      'Set cable to lowest position with straight bar or rope.',
      'Stand close and curl bar to shoulders.',
      'Lower with control.',
    ],
    youtubeUrl: 'https://www.youtube.com/watch?v=NFzTWp2qpiE',
    defaultSets: 3,
    defaultReps: 12,
  },
  {
    name: 'Overhead Tricep Extension',
    description: 'Stretches the long head of the tricep for full development.',
    category: 'Arms',
    difficulty: 'beginner',
    muscleGroups: ['Triceps'],
    equipment: ['Dumbbells', 'EZ Bar', 'Cable Machine'],
    instructions: [
      'Hold dumbbell overhead with both hands.',
      'Lower dumbbell behind head by bending elbows.',
      'Extend arms back to full overhead position.',
    ],
    youtubeUrl: 'https://www.youtube.com/watch?v=_gsUck-7M74',
    defaultSets: 3,
    defaultReps: 12,
  },
  {
    name: 'Preacher Curl',
    description: 'Curl on a preacher bench for strict bicep isolation.',
    category: 'Arms',
    difficulty: 'beginner',
    muscleGroups: ['Biceps', 'Brachialis'],
    equipment: ['Preacher Bench', 'Barbell', 'EZ Bar'],
    instructions: [
      'Rest upper arms on preacher pad, gripping bar.',
      'Curl bar upward to shoulder height.',
      'Lower with full control to near full extension.',
    ],
    youtubeUrl: 'https://www.youtube.com/watch?v=fIWP-FRFNU0',
    defaultSets: 3,
    defaultReps: 10,
  },
  {
    name: 'Close-Grip Bench Press',
    description: 'Narrow grip bench press for tricep mass and strength.',
    category: 'Arms',
    difficulty: 'intermediate',
    muscleGroups: ['Triceps', 'Chest', 'Front Deltoids'],
    equipment: ['Barbell', 'Bench'],
    instructions: [
      'Lie on bench, grip bar shoulder-width or narrower.',
      'Lower bar to lower chest, elbows tucked in.',
      'Press to full extension.',
    ],
    youtubeUrl: 'https://www.youtube.com/watch?v=nEF0bbd5UR4',
    defaultSets: 4,
    defaultReps: 8,
  },
  {
    name: 'Incline Dumbbell Curl',
    description:
      'Curl performed on an incline bench to increase the stretch on the bicep long head.',
    category: 'Arms',
    difficulty: 'intermediate',
    muscleGroups: ['Biceps'],
    equipment: ['Dumbbells', 'Incline Bench'],
    instructions: [
      'Sit on incline bench at 60°.',
      'Let dumbbells hang at full extension.',
      'Curl to shoulders, squeezing hard.',
      'Lower slowly to full stretch.',
    ],
    youtubeUrl: 'https://www.youtube.com/watch?v=MtBbMC5mBGU',
    defaultSets: 3,
    defaultReps: 12,
  },
  {
    name: 'Reverse Curl',
    description: 'Overhand grip curl for the brachioradialis and forearm development.',
    category: 'Arms',
    difficulty: 'beginner',
    muscleGroups: ['Brachioradialis', 'Forearms', 'Biceps'],
    equipment: ['Barbell', 'Dumbbells'],
    instructions: [
      'Hold bar with overhand grip.',
      'Curl to shoulder height.',
      'Lower with control.',
    ],
    youtubeUrl: 'https://www.youtube.com/watch?v=nRgxYX2Ve9w',
    defaultSets: 3,
    defaultReps: 12,
  },

  // ─── LEGS (15) ────────────────────────────────────────────────────────────
  {
    name: 'Back Squat',
    description:
      'The foundational lower-body strength exercise. Bar rests on traps, knees track over toes.',
    category: 'Legs',
    difficulty: 'intermediate',
    muscleGroups: ['Quads', 'Glutes', 'Hamstrings', 'Core'],
    equipment: ['Barbell', 'Squat Rack'],
    instructions: [
      'Set bar on upper traps, feet shoulder-width apart.',
      'Brace core and squat down until thighs are parallel.',
      'Drive through heels to stand back up.',
      'Keep chest up and knees tracking over toes.',
    ],
    youtubeUrl: 'https://www.youtube.com/watch?v=ultWZbUMPL8',
    defaultSets: 4,
    defaultReps: 6,
  },
  {
    name: 'Leg Press',
    description: 'Machine-based leg exercise for quad, glute, and hamstring development.',
    category: 'Legs',
    difficulty: 'beginner',
    muscleGroups: ['Quads', 'Glutes', 'Hamstrings'],
    equipment: ['Leg Press Machine'],
    instructions: [
      'Sit in leg press, feet shoulder-width on platform.',
      'Lower platform until knees reach 90°.',
      'Press platform away without locking knees.',
    ],
    youtubeUrl: 'https://www.youtube.com/watch?v=IZxyjW7MPJQ',
    defaultSets: 4,
    defaultReps: 10,
  },
  {
    name: 'Romanian Deadlift',
    description:
      'Hip-hinge movement targeting hamstrings and glutes through a long range of motion.',
    category: 'Legs',
    difficulty: 'intermediate',
    muscleGroups: ['Hamstrings', 'Glutes', 'Lower Back'],
    equipment: ['Barbell', 'Dumbbells'],
    instructions: [
      'Hold bar at hip height, soft bend in knees.',
      'Hinge at hips, pushing them back as bar lowers.',
      'Lower until you feel hamstring stretch.',
      'Drive hips forward to return to standing.',
    ],
    youtubeUrl: 'https://www.youtube.com/watch?v=hCDzSR6Ppis',
    defaultSets: 4,
    defaultReps: 8,
  },
  {
    name: 'Lunge',
    description: 'Unilateral leg exercise for quads, glutes, and balance.',
    category: 'Legs',
    difficulty: 'beginner',
    muscleGroups: ['Quads', 'Glutes', 'Hamstrings'],
    equipment: ['Dumbbells', 'Barbell'],
    instructions: [
      'Step forward with one foot, lower back knee toward floor.',
      'Keep front shin vertical and chest up.',
      'Push through front heel to return to start.',
      'Alternate legs.',
    ],
    youtubeUrl: 'https://www.youtube.com/watch?v=QOVaHwm-Q6U',
    defaultSets: 3,
    defaultReps: 12,
  },
  {
    name: 'Leg Curl',
    description: 'Machine isolation exercise for the hamstrings.',
    category: 'Legs',
    difficulty: 'beginner',
    muscleGroups: ['Hamstrings'],
    equipment: ['Leg Curl Machine'],
    instructions: [
      'Lie face down on machine, pad against lower legs.',
      'Curl legs toward glutes.',
      'Hold at top, then lower slowly.',
    ],
    youtubeUrl: 'https://www.youtube.com/watch?v=1Tq3QdYUuHs',
    defaultSets: 3,
    defaultReps: 12,
  },
  {
    name: 'Leg Extension',
    description: 'Machine isolation exercise for the quadriceps.',
    category: 'Legs',
    difficulty: 'beginner',
    muscleGroups: ['Quads'],
    equipment: ['Leg Extension Machine'],
    instructions: [
      'Sit in machine with pad on lower shins.',
      'Extend legs to fully straight.',
      'Lower slowly and repeat.',
    ],
    youtubeUrl: 'https://www.youtube.com/watch?v=YyvSfVjQeL0',
    defaultSets: 3,
    defaultReps: 15,
  },
  {
    name: 'Standing Calf Raise',
    description: 'Calf isolation exercise using a machine or bodyweight.',
    category: 'Legs',
    difficulty: 'beginner',
    muscleGroups: ['Calves', 'Soleus'],
    equipment: ['Calf Raise Machine'],
    instructions: [
      'Stand with balls of feet on the edge of the platform.',
      'Lower heels as far as comfortable.',
      'Rise onto tiptoes as high as possible.',
      'Hold at top briefly.',
    ],
    youtubeUrl: 'https://www.youtube.com/watch?v=-M4-G8p1fCI',
    defaultSets: 4,
    defaultReps: 20,
  },
  {
    name: 'Bulgarian Split Squat',
    description: 'Rear-foot elevated split squat for intense unilateral quad and glute work.',
    category: 'Legs',
    difficulty: 'advanced',
    muscleGroups: ['Quads', 'Glutes', 'Hamstrings'],
    equipment: ['Dumbbells', 'Bench'],
    instructions: [
      'Elevate back foot on bench.',
      'Lower front thigh to parallel.',
      'Press through front heel to return to start.',
    ],
    youtubeUrl: 'https://www.youtube.com/watch?v=2C-uNgKwPLE',
    defaultSets: 3,
    defaultReps: 10,
  },
  {
    name: 'Hip Thrust',
    description: 'Glute isolation exercise using a bench and barbell.',
    category: 'Legs',
    difficulty: 'intermediate',
    muscleGroups: ['Glutes', 'Hamstrings'],
    equipment: ['Barbell', 'Bench'],
    instructions: [
      'Lean upper back on bench, bar across hips.',
      'Drive hips up until body is straight.',
      'Squeeze glutes at top.',
      'Lower hips back down.',
    ],
    youtubeUrl: 'https://www.youtube.com/watch?v=LM8XHLYJoYs',
    defaultSets: 4,
    defaultReps: 12,
  },
  {
    name: 'Goblet Squat',
    description:
      'Front-loaded squat holding a dumbbell or kettlebell at chest. Great for beginners.',
    category: 'Legs',
    difficulty: 'beginner',
    muscleGroups: ['Quads', 'Glutes', 'Core'],
    equipment: ['Dumbbells', 'Kettlebell'],
    instructions: [
      'Hold dumbbell vertically at chest.',
      'Squat down keeping chest tall and elbows inside knees.',
      'Drive back to standing.',
    ],
    youtubeUrl: 'https://www.youtube.com/watch?v=MxsFDhcyFyE',
    defaultSets: 3,
    defaultReps: 12,
  },
  {
    name: 'Sumo Deadlift',
    description: 'Wide-stance deadlift variation that emphasizes glutes and inner thighs.',
    category: 'Legs',
    difficulty: 'advanced',
    muscleGroups: ['Glutes', 'Inner Thighs', 'Hamstrings', 'Lower Back'],
    equipment: ['Barbell'],
    instructions: [
      'Stance wider than shoulder-width, toes angled out.',
      'Grip bar inside legs, arms vertical.',
      'Push knees out and drive through floor to stand.',
    ],
    youtubeUrl: 'https://www.youtube.com/watch?v=Hj7pHSL8Kh8',
    defaultSets: 4,
    defaultReps: 5,
  },
  {
    name: 'Step-Up',
    description: 'Unilateral leg exercise stepping onto an elevated platform.',
    category: 'Legs',
    difficulty: 'beginner',
    muscleGroups: ['Quads', 'Glutes'],
    equipment: ['Dumbbells', 'Box', 'Bench'],
    instructions: [
      'Hold dumbbells at sides, stand facing a box.',
      'Step up with one foot, drive opposite knee up.',
      'Step back down and repeat.',
    ],
    youtubeUrl: 'https://www.youtube.com/watch?v=dQqApCGd5Ss',
    defaultSets: 3,
    defaultReps: 12,
  },
  {
    name: 'Wall Sit',
    description: 'Isometric quad exercise holding a seated position against a wall.',
    category: 'Legs',
    difficulty: 'beginner',
    muscleGroups: ['Quads', 'Glutes'],
    equipment: [],
    instructions: [
      'Stand with back against a wall.',
      'Slide down until thighs are parallel to floor.',
      'Hold for time, keeping core tight.',
    ],
    youtubeUrl: 'https://www.youtube.com/watch?v=y-wV4Wenf_4',
    defaultSets: 3,
    defaultReps: 1,
  },
  {
    name: 'Hack Squat',
    description: 'Machine squat variation for quad-dominant lower body work.',
    category: 'Legs',
    difficulty: 'intermediate',
    muscleGroups: ['Quads', 'Glutes'],
    equipment: ['Hack Squat Machine'],
    instructions: [
      'Position shoulders under pads, feet shoulder-width.',
      'Lower until thighs reach parallel.',
      'Press up to start without locking knees.',
    ],
    youtubeUrl: 'https://www.youtube.com/watch?v=0tn5K9NlCfo',
    defaultSets: 4,
    defaultReps: 10,
  },
  {
    name: 'Glute Bridge',
    description: 'Bodyweight glute exercise lying on the floor.',
    category: 'Legs',
    difficulty: 'beginner',
    muscleGroups: ['Glutes', 'Hamstrings', 'Core'],
    equipment: [],
    instructions: [
      'Lie on back, knees bent, feet flat.',
      'Drive hips up by squeezing glutes.',
      'Hold at top briefly.',
      'Lower with control.',
    ],
    youtubeUrl: 'https://www.youtube.com/watch?v=OUgsJ8-Vi0E',
    defaultSets: 3,
    defaultReps: 20,
  },

  // ─── CORE (10) ────────────────────────────────────────────────────────────
  {
    name: 'Plank',
    description: 'Isometric core stability exercise maintaining a straight body position.',
    category: 'Core',
    difficulty: 'beginner',
    muscleGroups: ['Core', 'Transverse Abdominis', 'Shoulders'],
    equipment: [],
    instructions: [
      'Start in a forearm plank position.',
      'Keep body in a straight line from head to heels.',
      'Engage core and glutes throughout.',
      'Hold for target time without letting hips sag.',
    ],
    youtubeUrl: 'https://www.youtube.com/watch?v=pSHjTRCQxIw',
    defaultSets: 3,
    defaultReps: 1,
  },
  {
    name: 'Ab Wheel Rollout',
    description: 'Advanced core exercise rolling out an ab wheel to full extension.',
    category: 'Core',
    difficulty: 'advanced',
    muscleGroups: ['Core', 'Lats', 'Shoulders'],
    equipment: ['Ab Wheel'],
    instructions: [
      'Kneel on floor, hands on ab wheel.',
      'Roll wheel forward until hips are nearly extended.',
      'Pull back to starting position.',
    ],
    youtubeUrl: 'https://www.youtube.com/watch?v=NkLbRrJYKGo',
    defaultSets: 3,
    defaultReps: 10,
  },
  {
    name: 'Hanging Leg Raise',
    description: 'Core exercise hanging from a pull-up bar, raising legs to parallel or higher.',
    category: 'Core',
    difficulty: 'intermediate',
    muscleGroups: ['Lower Abs', 'Hip Flexors'],
    equipment: ['Pull-Up Bar'],
    instructions: [
      'Hang from bar with hands shoulder-width.',
      'Raise legs to horizontal or higher.',
      'Lower with control without swinging.',
    ],
    youtubeUrl: 'https://www.youtube.com/watch?v=hdng3Nm1x_E',
    defaultSets: 3,
    defaultReps: 12,
  },
  {
    name: 'Russian Twist',
    description: 'Rotational core exercise for the obliques.',
    category: 'Core',
    difficulty: 'beginner',
    muscleGroups: ['Obliques', 'Core'],
    equipment: ['Dumbbells', 'Medicine Ball'],
    instructions: [
      'Sit with knees bent at 45°, lean back slightly.',
      'Hold weight and rotate torso side to side.',
      'Keep feet off ground for extra difficulty.',
    ],
    youtubeUrl: 'https://www.youtube.com/watch?v=wkD8rjkodUI',
    defaultSets: 3,
    defaultReps: 20,
  },
  {
    name: 'Cable Crunch',
    description: 'Weighted ab crunch using a cable machine for progressive overload.',
    category: 'Core',
    difficulty: 'beginner',
    muscleGroups: ['Rectus Abdominis', 'Obliques'],
    equipment: ['Cable Machine', 'Rope Attachment'],
    instructions: [
      'Kneel at cable machine, rope behind head.',
      'Crunch elbows toward knees, rounding the spine.',
      'Return slowly to starting position.',
    ],
    youtubeUrl: 'https://www.youtube.com/watch?v=2fbujeH3F0E',
    defaultSets: 3,
    defaultReps: 15,
  },
  {
    name: 'Bicycle Crunch',
    description: 'Dynamic crunch variation targeting both rectus abdominis and obliques.',
    category: 'Core',
    difficulty: 'beginner',
    muscleGroups: ['Rectus Abdominis', 'Obliques'],
    equipment: [],
    instructions: [
      'Lie on back, hands behind head.',
      'Bring opposite knee and elbow together while extending other leg.',
      'Alternate in a pedaling motion.',
    ],
    youtubeUrl: 'https://www.youtube.com/watch?v=9FGilxCbdz8',
    defaultSets: 3,
    defaultReps: 20,
  },
  {
    name: 'Pallof Press',
    description: 'Anti-rotation cable core exercise for core stability.',
    category: 'Core',
    difficulty: 'intermediate',
    muscleGroups: ['Core', 'Obliques', 'Transverse Abdominis'],
    equipment: ['Cable Machine'],
    instructions: [
      'Stand sideways to cable, hold handle at chest.',
      'Press cable straight out resisting rotation.',
      'Hold briefly, then pull back to chest.',
    ],
    youtubeUrl: 'https://www.youtube.com/watch?v=AH_QZLm_0-s',
    defaultSets: 3,
    defaultReps: 12,
  },
  {
    name: 'Dead Bug',
    description: 'Lying core stabilization exercise that trains anti-extension and coordination.',
    category: 'Core',
    difficulty: 'beginner',
    muscleGroups: ['Core', 'Transverse Abdominis'],
    equipment: [],
    instructions: [
      'Lie on back, arms vertical, hips and knees at 90°.',
      'Lower one arm and opposite leg toward the floor.',
      'Keep lower back pressed flat to the ground.',
      'Return and alternate sides.',
    ],
    youtubeUrl: 'https://www.youtube.com/watch?v=4XLEnwUr1d8',
    defaultSets: 3,
    defaultReps: 10,
  },
  {
    name: 'Hollow Body Hold',
    description: 'Gymnastics-based core exercise for total anterior chain tension.',
    category: 'Core',
    difficulty: 'intermediate',
    muscleGroups: ['Core', 'Hip Flexors', 'Lats'],
    equipment: [],
    instructions: [
      'Lie on back, arms extended overhead.',
      'Lift shoulders and legs off the ground.',
      'Hold the position maintaining a slight curve in the lower back.',
    ],
    youtubeUrl: 'https://www.youtube.com/watch?v=LlDNef_Ztsc',
    defaultSets: 3,
    defaultReps: 1,
  },
  {
    name: 'Woodchop',
    description: 'Rotational cable or band exercise mimicking chopping motion.',
    category: 'Core',
    difficulty: 'intermediate',
    muscleGroups: ['Obliques', 'Core', 'Shoulders'],
    equipment: ['Cable Machine', 'Resistance Band'],
    instructions: [
      'Set cable high and stand sideways.',
      'Pull cable diagonally down across body to opposite hip.',
      'Rotate through hips and torso.',
      'Return and repeat.',
    ],
    youtubeUrl: 'https://www.youtube.com/watch?v=pAplQXk3dkU',
    defaultSets: 3,
    defaultReps: 12,
  },

  // ─── CARDIO (8) ───────────────────────────────────────────────────────────
  {
    name: 'Treadmill Run',
    description: 'Steady-state cardiovascular exercise on a motorized treadmill.',
    category: 'Cardio',
    difficulty: 'beginner',
    muscleGroups: ['Quads', 'Hamstrings', 'Calves', 'Heart'],
    equipment: ['Treadmill'],
    instructions: [
      'Set treadmill to desired speed.',
      'Begin with a 5-minute warm-up walk.',
      'Run at target pace for planned duration.',
      'Cool down with a 5-minute walk.',
    ],
    youtubeUrl: 'https://www.youtube.com/watch?v=hQAJjwOhkjI',
    defaultSets: 1,
    defaultReps: 1,
  },
  {
    name: 'Cycling',
    description: 'Low-impact cardio on a stationary bike.',
    category: 'Cardio',
    difficulty: 'beginner',
    muscleGroups: ['Quads', 'Hamstrings', 'Calves', 'Glutes', 'Heart'],
    equipment: ['Stationary Bike'],
    instructions: [
      'Adjust seat height so knees are slightly bent at bottom of pedal stroke.',
      'Warm up for 5 minutes at low resistance.',
      'Cycle at target resistance and cadence.',
      'Cool down gradually.',
    ],
    youtubeUrl: 'https://www.youtube.com/watch?v=3HNl4XliBoY',
    defaultSets: 1,
    defaultReps: 1,
  },
  {
    name: 'Jump Rope',
    description: 'High-intensity cardio using a jump rope for conditioning and coordination.',
    category: 'Cardio',
    difficulty: 'beginner',
    muscleGroups: ['Calves', 'Shoulders', 'Heart'],
    equipment: ['Jump Rope'],
    instructions: [
      'Hold rope ends at hip height.',
      'Swing rope overhead and jump as it passes under feet.',
      'Land softly on balls of feet.',
      'Progress to double-unders as skill develops.',
    ],
    youtubeUrl: 'https://www.youtube.com/watch?v=FJmRQ5iTXKE',
    defaultSets: 3,
    defaultReps: 1,
  },
  {
    name: 'Rowing Machine',
    description: 'Full-body low-impact cardio on an ergometer rowing machine.',
    category: 'Cardio',
    difficulty: 'intermediate',
    muscleGroups: ['Back', 'Quads', 'Arms', 'Core', 'Heart'],
    equipment: ['Rowing Machine'],
    instructions: [
      'Strap feet in, sit with knees bent.',
      'Lean forward and grab handle.',
      'Drive through legs, then lean back and pull to chest.',
      'Return with control: arms, torso, then legs.',
    ],
    youtubeUrl: 'https://www.youtube.com/watch?v=H0r_D_ODuBU',
    defaultSets: 1,
    defaultReps: 1,
  },
  {
    name: 'Box Jump',
    description: 'Explosive plyometric jump onto a box for power and cardio.',
    category: 'Cardio',
    difficulty: 'intermediate',
    muscleGroups: ['Quads', 'Glutes', 'Calves', 'Core'],
    equipment: ['Plyometric Box'],
    instructions: [
      'Stand in front of box, feet shoulder-width.',
      'Dip, swing arms, and jump explosively onto box.',
      'Land softly with bent knees.',
      'Step or jump back down.',
    ],
    youtubeUrl: 'https://www.youtube.com/watch?v=52r_Ul5k18g',
    defaultSets: 4,
    defaultReps: 8,
  },
  {
    name: 'Battle Ropes',
    description: 'High-intensity upper body and cardiovascular conditioning with heavy ropes.',
    category: 'Cardio',
    difficulty: 'intermediate',
    muscleGroups: ['Shoulders', 'Arms', 'Core', 'Heart'],
    equipment: ['Battle Ropes'],
    instructions: [
      'Hold one end of rope in each hand.',
      'Alternate arms creating waves in the rope.',
      'Keep core tight and knees slightly bent.',
      'Maintain intensity for set time.',
    ],
    youtubeUrl: 'https://www.youtube.com/watch?v=roCjMlqPQRk',
    defaultSets: 4,
    defaultReps: 1,
  },
  {
    name: 'Stair Climber',
    description: 'Low-impact step cardio on a stair climber machine.',
    category: 'Cardio',
    difficulty: 'beginner',
    muscleGroups: ['Quads', 'Glutes', 'Calves', 'Heart'],
    equipment: ['Stair Climber Machine'],
    instructions: [
      'Step on machine and set desired speed.',
      'Walk at consistent pace without gripping rails.',
      'Drive through heels for more glute activation.',
    ],
    youtubeUrl: 'https://www.youtube.com/watch?v=nBr6Y1SSeoo',
    defaultSets: 1,
    defaultReps: 1,
  },
  {
    name: 'Sprint Intervals',
    description: 'High-intensity interval training alternating between sprints and rest.',
    category: 'Cardio',
    difficulty: 'advanced',
    muscleGroups: ['Quads', 'Hamstrings', 'Glutes', 'Calves', 'Heart'],
    equipment: [],
    instructions: [
      'Warm up with 5-minute jog.',
      'Sprint at 90–100% effort for 20–30 seconds.',
      'Rest or walk for 90 seconds.',
      'Repeat 8–10 rounds.',
      'Cool down with 5-minute walk.',
    ],
    youtubeUrl: 'https://www.youtube.com/watch?v=fZpzLb4Jq30',
    defaultSets: 8,
    defaultReps: 1,
  },

  // ─── FULL BODY (8) ────────────────────────────────────────────────────────
  {
    name: 'Burpee',
    description: 'Full-body conditioning exercise combining a squat, plank, push-up, and jump.',
    category: 'Full Body',
    difficulty: 'intermediate',
    muscleGroups: ['Chest', 'Core', 'Quads', 'Shoulders', 'Heart'],
    equipment: [],
    instructions: [
      'Start standing.',
      'Squat down and place hands on floor.',
      'Jump feet back to plank.',
      'Perform a push-up.',
      'Jump feet back in and jump up with arms overhead.',
    ],
    youtubeUrl: 'https://www.youtube.com/watch?v=dZgVxmf6jkA',
    defaultSets: 4,
    defaultReps: 10,
  },
  {
    name: 'Kettlebell Swing',
    description: 'Hip-hinge power exercise for posterior chain and cardiovascular conditioning.',
    category: 'Full Body',
    difficulty: 'intermediate',
    muscleGroups: ['Glutes', 'Hamstrings', 'Core', 'Shoulders', 'Back'],
    equipment: ['Kettlebell'],
    instructions: [
      'Hold kettlebell with both hands, feet shoulder-width.',
      'Hinge at hips and swing kettlebell back between legs.',
      'Drive hips forward explosively to swing kettlebell to chest height.',
      'Hinge back to repeat.',
    ],
    youtubeUrl: 'https://www.youtube.com/watch?v=YSxHifyI6s8',
    defaultSets: 4,
    defaultReps: 15,
  },
  {
    name: 'Clean and Press',
    description: 'Olympic-style compound movement from floor to overhead press.',
    category: 'Full Body',
    difficulty: 'advanced',
    muscleGroups: ['Quads', 'Glutes', 'Back', 'Traps', 'Shoulders', 'Arms'],
    equipment: ['Barbell', 'Dumbbells'],
    instructions: [
      'Start with weight at thighs.',
      'Clean weight to shoulder height explosively.',
      'Press overhead to full extension.',
      'Lower back to shoulders, then to hips.',
    ],
    youtubeUrl: 'https://www.youtube.com/watch?v=gl2e6KeJ-6U',
    defaultSets: 4,
    defaultReps: 5,
  },
  {
    name: 'Thruster',
    description:
      'Front squat to overhead press combination used in CrossFit and functional training.',
    category: 'Full Body',
    difficulty: 'advanced',
    muscleGroups: ['Quads', 'Glutes', 'Shoulders', 'Triceps', 'Core'],
    equipment: ['Barbell', 'Dumbbells', 'Kettlebell'],
    instructions: [
      'Hold bar at shoulder height, front rack.',
      'Squat to parallel.',
      'Drive up and press bar overhead in one fluid motion.',
      'Lower back to shoulders as you descend.',
    ],
    youtubeUrl: 'https://www.youtube.com/watch?v=ioHCgyHoOcE',
    defaultSets: 3,
    defaultReps: 8,
  },
  {
    name: 'Turkish Get-Up',
    description: 'Full-body movement getting from lying to standing with a weight overhead.',
    category: 'Full Body',
    difficulty: 'advanced',
    muscleGroups: ['Core', 'Shoulders', 'Glutes', 'Hips', 'Legs'],
    equipment: ['Kettlebell', 'Dumbbells'],
    instructions: [
      'Lie on back with one arm straight up holding weight.',
      'Roll to elbow, then hand.',
      'Sweep leg under to kneeling.',
      'Stand up maintaining the weight overhead.',
      'Reverse the sequence to return to floor.',
    ],
    youtubeUrl: 'https://www.youtube.com/watch?v=jFK4bZuZXME',
    defaultSets: 3,
    defaultReps: 3,
  },
  {
    name: 'Man Maker',
    description: 'Combination of renegade rows, push-up, and squat clean-to-press.',
    category: 'Full Body',
    difficulty: 'advanced',
    muscleGroups: ['Back', 'Chest', 'Shoulders', 'Core', 'Quads', 'Arms'],
    equipment: ['Dumbbells'],
    instructions: [
      'Start in plank position holding dumbbells.',
      'Perform a row with each arm.',
      'Do a push-up.',
      'Jump feet in and clean dumbbells to shoulders.',
      'Press overhead.',
    ],
    youtubeUrl: 'https://www.youtube.com/watch?v=DJPapMVtbJM',
    defaultSets: 3,
    defaultReps: 5,
  },
  {
    name: 'Sandbag Carry',
    description: 'Loaded carry for full-body strength and conditioning.',
    category: 'Full Body',
    difficulty: 'intermediate',
    muscleGroups: ['Core', 'Glutes', 'Back', 'Shoulders', 'Legs'],
    equipment: ['Sandbag'],
    instructions: [
      'Pick up sandbag and carry on shoulder or at chest.',
      'Walk for prescribed distance or time.',
      'Maintain upright posture throughout.',
    ],
    youtubeUrl: 'https://www.youtube.com/watch?v=9fL6pf39vVg',
    defaultSets: 3,
    defaultReps: 1,
  },
  {
    name: 'Mountain Climber',
    description: 'Dynamic plank exercise alternating knees toward chest for core and cardio.',
    category: 'Full Body',
    difficulty: 'beginner',
    muscleGroups: ['Core', 'Shoulders', 'Hip Flexors', 'Heart'],
    equipment: [],
    instructions: [
      'Start in high plank position.',
      'Drive one knee toward chest, then switch.',
      'Alternate rapidly maintaining a flat back.',
    ],
    youtubeUrl: 'https://www.youtube.com/watch?v=nmwgirgXLYM',
    defaultSets: 3,
    defaultReps: 20,
  },
];

async function seed() {
  // Count existing exercises
  const result = await db.execute(sql`SELECT COUNT(*) as count FROM exercises`);
  const count = Number((result.rows[0] as any).count);

  if (count > 0) {
    console.log(`ℹ️  Exercises table already has ${count} rows — skipping seed.`);
    console.log('   To re-seed, truncate the exercises table first.');
    process.exit(0);
  }

  console.log(`🌱 Seeding ${EXERCISES.length} exercises...`);

  for (const exercise of EXERCISES) {
    await db.insert(exercises).values({
      name: exercise.name,
      description: exercise.description,
      category: exercise.category,
      difficulty: exercise.difficulty,
      muscleGroups: exercise.muscleGroups,
      equipment: exercise.equipment,
      instructions: exercise.instructions,
      youtubeUrl: exercise.youtubeUrl ?? null,
      defaultSets: exercise.defaultSets ?? 3,
      defaultReps: exercise.defaultReps ?? 10,
    });
  }

  console.log(`✅ Successfully seeded ${EXERCISES.length} exercises across 8 categories.`);
  process.exit(0);
}

seed().catch((err) => {
  console.error('❌ Seed failed:', err);
  process.exit(1);
});
