// Server-side Achievement Definitions for database seeding
// Mirrors client/src/lib/constants/achievements.ts

export interface AchievementSeed {
  name: string;
  description: string;
  category: string;
  requirementType: string;
  requirementValue: string; // decimal column — must be string
  xpReward: number;
  badgeIcon: string;
  isHidden: boolean;
}

export const ACHIEVEMENT_SEEDS: AchievementSeed[] = [
  // ==================== CONSISTENCY ====================
  {
    name: 'First Step',
    description: 'Complete your first workout',
    category: 'consistency',
    requirementType: 'total_workouts',
    requirementValue: '1',
    xpReward: 50,
    badgeIcon: 'footprints',
    isHidden: false,
  },
  {
    name: 'Getting Started',
    description: 'Complete 5 workouts',
    category: 'consistency',
    requirementType: 'total_workouts',
    requirementValue: '5',
    xpReward: 100,
    badgeIcon: 'trending-up',
    isHidden: false,
  },
  {
    name: 'Creature of Habit',
    description: 'Complete 25 workouts',
    category: 'consistency',
    requirementType: 'total_workouts',
    requirementValue: '25',
    xpReward: 300,
    badgeIcon: 'calendar',
    isHidden: false,
  },
  {
    name: 'Century Club',
    description: 'Complete 100 workouts',
    category: 'consistency',
    requirementType: 'total_workouts',
    requirementValue: '100',
    xpReward: 2000,
    badgeIcon: 'trophy',
    isHidden: false,
  },
  {
    name: 'Gym Veteran',
    description: 'Complete 500 workouts',
    category: 'consistency',
    requirementType: 'total_workouts',
    requirementValue: '500',
    xpReward: 5000,
    badgeIcon: 'medal',
    isHidden: true,
  },
  {
    name: 'Week Warrior',
    description: 'Maintain a 7-day workout streak',
    category: 'consistency',
    requirementType: 'streak_days',
    requirementValue: '7',
    xpReward: 200,
    badgeIcon: 'flame',
    isHidden: false,
  },
  {
    name: 'Two Week Terror',
    description: 'Maintain a 14-day workout streak',
    category: 'consistency',
    requirementType: 'streak_days',
    requirementValue: '14',
    xpReward: 400,
    badgeIcon: 'flame',
    isHidden: false,
  },
  {
    name: 'Iron Will',
    description: 'Maintain a 30-day workout streak',
    category: 'consistency',
    requirementType: 'streak_days',
    requirementValue: '30',
    xpReward: 1000,
    badgeIcon: 'zap',
    isHidden: false,
  },
  {
    name: 'Unstoppable Force',
    description: 'Maintain a 100-day workout streak',
    category: 'consistency',
    requirementType: 'streak_days',
    requirementValue: '100',
    xpReward: 5000,
    badgeIcon: 'zap',
    isHidden: true,
  },
  {
    name: 'Legendary',
    description: 'Maintain a 365-day workout streak',
    category: 'consistency',
    requirementType: 'streak_days',
    requirementValue: '365',
    xpReward: 10000,
    badgeIcon: 'crown',
    isHidden: true,
  },

  // ==================== STRENGTH ====================
  {
    name: 'PR Hunter',
    description: 'Set 10 personal records',
    category: 'strength',
    requirementType: 'total_prs',
    requirementValue: '10',
    xpReward: 500,
    badgeIcon: 'target',
    isHidden: false,
  },
  {
    name: 'PR Machine',
    description: 'Set 50 personal records',
    category: 'strength',
    requirementType: 'total_prs',
    requirementValue: '50',
    xpReward: 1500,
    badgeIcon: 'target',
    isHidden: false,
  },
  {
    name: 'Record Breaker',
    description: 'Set 100 personal records',
    category: 'strength',
    requirementType: 'total_prs',
    requirementValue: '100',
    xpReward: 3000,
    badgeIcon: 'award',
    isHidden: false,
  },
  {
    name: 'One Plate Club (Bench)',
    description: 'Bench press 60kg (135lbs)',
    category: 'strength',
    requirementType: 'exercise_1rm',
    requirementValue: '60',
    xpReward: 500,
    badgeIcon: 'dumbbell',
    isHidden: false,
  },
  {
    name: 'Two Plate Club (Bench)',
    description: 'Bench press 100kg (225lbs)',
    category: 'strength',
    requirementType: 'exercise_1rm',
    requirementValue: '100',
    xpReward: 1000,
    badgeIcon: 'dumbbell',
    isHidden: false,
  },
  {
    name: 'Three Plate Club (Bench)',
    description: 'Bench press 140kg (315lbs)',
    category: 'strength',
    requirementType: 'exercise_1rm',
    requirementValue: '140',
    xpReward: 2500,
    badgeIcon: 'dumbbell',
    isHidden: true,
  },
  {
    name: 'Two Plate Club (Squat)',
    description: 'Squat 100kg (225lbs)',
    category: 'strength',
    requirementType: 'exercise_1rm',
    requirementValue: '100',
    xpReward: 750,
    badgeIcon: 'dumbbell',
    isHidden: false,
  },
  {
    name: 'Three Plate Club (Squat)',
    description: 'Squat 140kg (315lbs)',
    category: 'strength',
    requirementType: 'exercise_1rm',
    requirementValue: '140',
    xpReward: 1500,
    badgeIcon: 'dumbbell',
    isHidden: false,
  },
  {
    name: 'Four Plate Club (Squat)',
    description: 'Squat 180kg (405lbs)',
    category: 'strength',
    requirementType: 'exercise_1rm',
    requirementValue: '180',
    xpReward: 3000,
    badgeIcon: 'dumbbell',
    isHidden: true,
  },
  {
    name: 'Two Plate Club (Deadlift)',
    description: 'Deadlift 100kg (225lbs)',
    category: 'strength',
    requirementType: 'exercise_1rm',
    requirementValue: '100',
    xpReward: 500,
    badgeIcon: 'dumbbell',
    isHidden: false,
  },
  {
    name: 'Three Plate Club (Deadlift)',
    description: 'Deadlift 140kg (315lbs)',
    category: 'strength',
    requirementType: 'exercise_1rm',
    requirementValue: '140',
    xpReward: 1000,
    badgeIcon: 'dumbbell',
    isHidden: false,
  },
  {
    name: 'Four Plate Club (Deadlift)',
    description: 'Deadlift 180kg (405lbs)',
    category: 'strength',
    requirementType: 'exercise_1rm',
    requirementValue: '180',
    xpReward: 2000,
    badgeIcon: 'dumbbell',
    isHidden: false,
  },
  {
    name: 'Five Plate Club (Deadlift)',
    description: 'Deadlift 220kg (500lbs)',
    category: 'strength',
    requirementType: 'exercise_1rm',
    requirementValue: '220',
    xpReward: 5000,
    badgeIcon: 'dumbbell',
    isHidden: true,
  },
  {
    name: 'Intermediate Lifter',
    description: 'Reach Intermediate strength on any lift',
    category: 'strength',
    requirementType: 'strength_classification',
    requirementValue: '3',
    xpReward: 500,
    badgeIcon: 'bar-chart',
    isHidden: false,
  },
  {
    name: 'Advanced Lifter',
    description: 'Reach Advanced strength on any lift',
    category: 'strength',
    requirementType: 'strength_classification',
    requirementValue: '4',
    xpReward: 2000,
    badgeIcon: 'bar-chart-2',
    isHidden: false,
  },
  {
    name: 'Elite Status',
    description: 'Reach Elite strength on any lift',
    category: 'strength',
    requirementType: 'strength_classification',
    requirementValue: '5',
    xpReward: 5000,
    badgeIcon: 'star',
    isHidden: true,
  },

  // ==================== VOLUME ====================
  {
    name: 'Volume Veteran',
    description: 'Lift 10,000 kg total',
    category: 'volume',
    requirementType: 'total_volume',
    requirementValue: '10000',
    xpReward: 100,
    badgeIcon: 'scale',
    isHidden: false,
  },
  {
    name: 'Heavy Lifter',
    description: 'Lift 50,000 kg total',
    category: 'volume',
    requirementType: 'total_volume',
    requirementValue: '50000',
    xpReward: 300,
    badgeIcon: 'scale',
    isHidden: false,
  },
  {
    name: 'Ton Lifter',
    description: 'Lift 100,000 kg total',
    category: 'volume',
    requirementType: 'total_volume',
    requirementValue: '100000',
    xpReward: 500,
    badgeIcon: 'scale',
    isHidden: false,
  },
  {
    name: 'Half Million Club',
    description: 'Lift 500,000 kg total',
    category: 'volume',
    requirementType: 'total_volume',
    requirementValue: '500000',
    xpReward: 2500,
    badgeIcon: 'weight',
    isHidden: false,
  },
  {
    name: 'Million Pound Club',
    description: 'Lift 1,000,000 kg total',
    category: 'volume',
    requirementType: 'total_volume',
    requirementValue: '1000000',
    xpReward: 5000,
    badgeIcon: 'weight',
    isHidden: true,
  },
  {
    name: 'Rep Machine',
    description: 'Complete 10,000 total reps',
    category: 'volume',
    requirementType: 'total_reps',
    requirementValue: '10000',
    xpReward: 500,
    badgeIcon: 'repeat',
    isHidden: false,
  },
  {
    name: 'Set Master',
    description: 'Complete 1,000 total sets',
    category: 'volume',
    requirementType: 'total_sets',
    requirementValue: '1000',
    xpReward: 300,
    badgeIcon: 'layers',
    isHidden: false,
  },

  // ==================== EXPLORATION ====================
  {
    name: 'Curious Mind',
    description: 'Try 10 different exercises',
    category: 'exploration',
    requirementType: 'unique_exercises',
    requirementValue: '10',
    xpReward: 100,
    badgeIcon: 'search',
    isHidden: false,
  },
  {
    name: 'Exercise Explorer',
    description: 'Try 50 different exercises',
    category: 'exploration',
    requirementType: 'unique_exercises',
    requirementValue: '50',
    xpReward: 500,
    badgeIcon: 'compass',
    isHidden: false,
  },
  {
    name: 'Movement Master',
    description: 'Try 100 different exercises',
    category: 'exploration',
    requirementType: 'unique_exercises',
    requirementValue: '100',
    xpReward: 1500,
    badgeIcon: 'map',
    isHidden: false,
  },
  {
    name: 'Full Body Master',
    description: 'Train all major muscle groups in a week',
    category: 'exploration',
    requirementType: 'weekly_muscle_groups',
    requirementValue: '12',
    xpReward: 200,
    badgeIcon: 'user',
    isHidden: false,
  },
  {
    name: 'Well Rounded',
    description: 'Complete workouts in 5 different categories',
    category: 'exploration',
    requirementType: 'workout_categories',
    requirementValue: '5',
    xpReward: 300,
    badgeIcon: 'pie-chart',
    isHidden: false,
  },

  // ==================== SOCIAL ====================
  {
    name: 'Mentor',
    description: 'Have 5 clients set personal records',
    category: 'social',
    requirementType: 'client_prs',
    requirementValue: '5',
    xpReward: 500,
    badgeIcon: 'users',
    isHidden: false,
  },
  {
    name: 'Coach',
    description: 'Have 25 client workout completions',
    category: 'social',
    requirementType: 'client_workouts',
    requirementValue: '25',
    xpReward: 750,
    badgeIcon: 'clipboard',
    isHidden: false,
  },
  {
    name: 'Team Builder',
    description: 'Have 10 active clients',
    category: 'social',
    requirementType: 'active_clients',
    requirementValue: '10',
    xpReward: 1000,
    badgeIcon: 'users-round',
    isHidden: false,
  },
  {
    name: 'Transformation Specialist',
    description: 'Have 3 clients reach their goals',
    category: 'social',
    requirementType: 'client_goals_achieved',
    requirementValue: '3',
    xpReward: 2000,
    badgeIcon: 'sparkles',
    isHidden: false,
  },

  // ==================== NUTRITION ====================
  {
    name: 'Food Logger',
    description: 'Log 50 meals',
    category: 'nutrition',
    requirementType: 'meals_logged',
    requirementValue: '50',
    xpReward: 200,
    badgeIcon: 'utensils',
    isHidden: false,
  },
  {
    name: 'Macro Master',
    description: 'Hit your macro targets 7 days in a row',
    category: 'nutrition',
    requirementType: 'macro_streak',
    requirementValue: '7',
    xpReward: 300,
    badgeIcon: 'pie-chart',
    isHidden: false,
  },
  {
    name: 'Meal Prep Pro',
    description: 'Create 5 meal plans',
    category: 'nutrition',
    requirementType: 'meal_plans_created',
    requirementValue: '5',
    xpReward: 250,
    badgeIcon: 'clipboard-list',
    isHidden: false,
  },
];
