// Achievement Definitions for GymGurus
// These are the base achievement templates that will be seeded into the database

export interface AchievementDefinition {
  name: string;
  description: string;
  category: 'consistency' | 'strength' | 'volume' | 'exploration' | 'social' | 'nutrition';
  requirementType: string;
  requirementValue: number;
  exerciseFilter?: string; // For exercise-specific achievements
  xpReward: number;
  isHidden?: boolean;
  badgeIcon?: string;
}

export const ACHIEVEMENT_DEFINITIONS: AchievementDefinition[] = [
  // ==================== CONSISTENCY ====================
  {
    name: 'First Step',
    description: 'Complete your first workout',
    category: 'consistency',
    requirementType: 'total_workouts',
    requirementValue: 1,
    xpReward: 50,
    badgeIcon: 'footprints',
  },
  {
    name: 'Getting Started',
    description: 'Complete 5 workouts',
    category: 'consistency',
    requirementType: 'total_workouts',
    requirementValue: 5,
    xpReward: 100,
    badgeIcon: 'trending-up',
  },
  {
    name: 'Creature of Habit',
    description: 'Complete 25 workouts',
    category: 'consistency',
    requirementType: 'total_workouts',
    requirementValue: 25,
    xpReward: 300,
    badgeIcon: 'calendar',
  },
  {
    name: 'Century Club',
    description: 'Complete 100 workouts',
    category: 'consistency',
    requirementType: 'total_workouts',
    requirementValue: 100,
    xpReward: 2000,
    badgeIcon: 'trophy',
  },
  {
    name: 'Gym Veteran',
    description: 'Complete 500 workouts',
    category: 'consistency',
    requirementType: 'total_workouts',
    requirementValue: 500,
    xpReward: 5000,
    isHidden: true,
    badgeIcon: 'medal',
  },
  {
    name: 'Week Warrior',
    description: 'Maintain a 7-day workout streak',
    category: 'consistency',
    requirementType: 'streak_days',
    requirementValue: 7,
    xpReward: 200,
    badgeIcon: 'flame',
  },
  {
    name: 'Two Week Terror',
    description: 'Maintain a 14-day workout streak',
    category: 'consistency',
    requirementType: 'streak_days',
    requirementValue: 14,
    xpReward: 400,
    badgeIcon: 'flame',
  },
  {
    name: 'Iron Will',
    description: 'Maintain a 30-day workout streak',
    category: 'consistency',
    requirementType: 'streak_days',
    requirementValue: 30,
    xpReward: 1000,
    badgeIcon: 'zap',
  },
  {
    name: 'Unstoppable Force',
    description: 'Maintain a 100-day workout streak',
    category: 'consistency',
    requirementType: 'streak_days',
    requirementValue: 100,
    xpReward: 5000,
    isHidden: true,
    badgeIcon: 'zap',
  },
  {
    name: 'Legendary',
    description: 'Maintain a 365-day workout streak',
    category: 'consistency',
    requirementType: 'streak_days',
    requirementValue: 365,
    xpReward: 10000,
    isHidden: true,
    badgeIcon: 'crown',
  },

  // ==================== STRENGTH ====================
  {
    name: 'PR Hunter',
    description: 'Set 10 personal records',
    category: 'strength',
    requirementType: 'total_prs',
    requirementValue: 10,
    xpReward: 500,
    badgeIcon: 'target',
  },
  {
    name: 'PR Machine',
    description: 'Set 50 personal records',
    category: 'strength',
    requirementType: 'total_prs',
    requirementValue: 50,
    xpReward: 1500,
    badgeIcon: 'target',
  },
  {
    name: 'Record Breaker',
    description: 'Set 100 personal records',
    category: 'strength',
    requirementType: 'total_prs',
    requirementValue: 100,
    xpReward: 3000,
    badgeIcon: 'award',
  },
  {
    name: 'One Plate Club (Bench)',
    description: 'Bench press 60kg (135lbs)',
    category: 'strength',
    requirementType: 'exercise_1rm',
    requirementValue: 60,
    exerciseFilter: 'bench_press',
    xpReward: 500,
    badgeIcon: 'dumbbell',
  },
  {
    name: 'Two Plate Club (Bench)',
    description: 'Bench press 100kg (225lbs)',
    category: 'strength',
    requirementType: 'exercise_1rm',
    requirementValue: 100,
    exerciseFilter: 'bench_press',
    xpReward: 1000,
    badgeIcon: 'dumbbell',
  },
  {
    name: 'Three Plate Club (Bench)',
    description: 'Bench press 140kg (315lbs)',
    category: 'strength',
    requirementType: 'exercise_1rm',
    requirementValue: 140,
    exerciseFilter: 'bench_press',
    xpReward: 2500,
    isHidden: true,
    badgeIcon: 'dumbbell',
  },
  {
    name: 'Two Plate Club (Squat)',
    description: 'Squat 100kg (225lbs)',
    category: 'strength',
    requirementType: 'exercise_1rm',
    requirementValue: 100,
    exerciseFilter: 'squat',
    xpReward: 750,
    badgeIcon: 'dumbbell',
  },
  {
    name: 'Three Plate Club (Squat)',
    description: 'Squat 140kg (315lbs)',
    category: 'strength',
    requirementType: 'exercise_1rm',
    requirementValue: 140,
    exerciseFilter: 'squat',
    xpReward: 1500,
    badgeIcon: 'dumbbell',
  },
  {
    name: 'Four Plate Club (Squat)',
    description: 'Squat 180kg (405lbs)',
    category: 'strength',
    requirementType: 'exercise_1rm',
    requirementValue: 180,
    exerciseFilter: 'squat',
    xpReward: 3000,
    isHidden: true,
    badgeIcon: 'dumbbell',
  },
  {
    name: 'Two Plate Club (Deadlift)',
    description: 'Deadlift 100kg (225lbs)',
    category: 'strength',
    requirementType: 'exercise_1rm',
    requirementValue: 100,
    exerciseFilter: 'deadlift',
    xpReward: 500,
    badgeIcon: 'dumbbell',
  },
  {
    name: 'Three Plate Club (Deadlift)',
    description: 'Deadlift 140kg (315lbs)',
    category: 'strength',
    requirementType: 'exercise_1rm',
    requirementValue: 140,
    exerciseFilter: 'deadlift',
    xpReward: 1000,
    badgeIcon: 'dumbbell',
  },
  {
    name: 'Four Plate Club (Deadlift)',
    description: 'Deadlift 180kg (405lbs)',
    category: 'strength',
    requirementType: 'exercise_1rm',
    requirementValue: 180,
    exerciseFilter: 'deadlift',
    xpReward: 2000,
    badgeIcon: 'dumbbell',
  },
  {
    name: 'Five Plate Club (Deadlift)',
    description: 'Deadlift 220kg (500lbs)',
    category: 'strength',
    requirementType: 'exercise_1rm',
    requirementValue: 220,
    exerciseFilter: 'deadlift',
    xpReward: 5000,
    isHidden: true,
    badgeIcon: 'dumbbell',
  },
  {
    name: 'Intermediate Lifter',
    description: 'Reach Intermediate strength on any lift',
    category: 'strength',
    requirementType: 'strength_classification',
    requirementValue: 3, // Intermediate = 3
    xpReward: 500,
    badgeIcon: 'bar-chart',
  },
  {
    name: 'Advanced Lifter',
    description: 'Reach Advanced strength on any lift',
    category: 'strength',
    requirementType: 'strength_classification',
    requirementValue: 4, // Advanced = 4
    xpReward: 2000,
    badgeIcon: 'bar-chart-2',
  },
  {
    name: 'Elite Status',
    description: 'Reach Elite strength on any lift',
    category: 'strength',
    requirementType: 'strength_classification',
    requirementValue: 5, // Elite = 5
    xpReward: 5000,
    isHidden: true,
    badgeIcon: 'star',
  },

  // ==================== VOLUME ====================
  {
    name: 'Volume Veteran',
    description: 'Lift 10,000 kg total',
    category: 'volume',
    requirementType: 'total_volume',
    requirementValue: 10000,
    xpReward: 100,
    badgeIcon: 'scale',
  },
  {
    name: 'Heavy Lifter',
    description: 'Lift 50,000 kg total',
    category: 'volume',
    requirementType: 'total_volume',
    requirementValue: 50000,
    xpReward: 300,
    badgeIcon: 'scale',
  },
  {
    name: 'Ton Lifter',
    description: 'Lift 100,000 kg total',
    category: 'volume',
    requirementType: 'total_volume',
    requirementValue: 100000,
    xpReward: 500,
    badgeIcon: 'scale',
  },
  {
    name: 'Half Million Club',
    description: 'Lift 500,000 kg total',
    category: 'volume',
    requirementType: 'total_volume',
    requirementValue: 500000,
    xpReward: 2500,
    badgeIcon: 'weight',
  },
  {
    name: 'Million Pound Club',
    description: 'Lift 1,000,000 kg total',
    category: 'volume',
    requirementType: 'total_volume',
    requirementValue: 1000000,
    xpReward: 5000,
    isHidden: true,
    badgeIcon: 'weight',
  },
  {
    name: 'Rep Machine',
    description: 'Complete 10,000 total reps',
    category: 'volume',
    requirementType: 'total_reps',
    requirementValue: 10000,
    xpReward: 500,
    badgeIcon: 'repeat',
  },
  {
    name: 'Set Master',
    description: 'Complete 1,000 total sets',
    category: 'volume',
    requirementType: 'total_sets',
    requirementValue: 1000,
    xpReward: 300,
    badgeIcon: 'layers',
  },

  // ==================== EXPLORATION ====================
  {
    name: 'Curious Mind',
    description: 'Try 10 different exercises',
    category: 'exploration',
    requirementType: 'unique_exercises',
    requirementValue: 10,
    xpReward: 100,
    badgeIcon: 'search',
  },
  {
    name: 'Exercise Explorer',
    description: 'Try 50 different exercises',
    category: 'exploration',
    requirementType: 'unique_exercises',
    requirementValue: 50,
    xpReward: 500,
    badgeIcon: 'compass',
  },
  {
    name: 'Movement Master',
    description: 'Try 100 different exercises',
    category: 'exploration',
    requirementType: 'unique_exercises',
    requirementValue: 100,
    xpReward: 1500,
    badgeIcon: 'map',
  },
  {
    name: 'Full Body Master',
    description: 'Train all major muscle groups in a week',
    category: 'exploration',
    requirementType: 'weekly_muscle_groups',
    requirementValue: 12, // All major muscle groups
    xpReward: 200,
    badgeIcon: 'user',
  },
  {
    name: 'Well Rounded',
    description: 'Complete workouts in 5 different categories',
    category: 'exploration',
    requirementType: 'workout_categories',
    requirementValue: 5,
    xpReward: 300,
    badgeIcon: 'pie-chart',
  },

  // ==================== SOCIAL (Trainer-specific) ====================
  {
    name: 'Mentor',
    description: 'Have 5 clients set personal records',
    category: 'social',
    requirementType: 'client_prs',
    requirementValue: 5,
    xpReward: 500,
    badgeIcon: 'users',
  },
  {
    name: 'Coach',
    description: 'Have 25 client workout completions',
    category: 'social',
    requirementType: 'client_workouts',
    requirementValue: 25,
    xpReward: 750,
    badgeIcon: 'clipboard',
  },
  {
    name: 'Team Builder',
    description: 'Have 10 active clients',
    category: 'social',
    requirementType: 'active_clients',
    requirementValue: 10,
    xpReward: 1000,
    badgeIcon: 'users-round',
  },
  {
    name: 'Transformation Specialist',
    description: 'Have 3 clients reach their goals',
    category: 'social',
    requirementType: 'client_goals_achieved',
    requirementValue: 3,
    xpReward: 2000,
    badgeIcon: 'sparkles',
  },

  // ==================== NUTRITION ====================
  {
    name: 'Food Logger',
    description: 'Log 50 meals',
    category: 'nutrition',
    requirementType: 'meals_logged',
    requirementValue: 50,
    xpReward: 200,
    badgeIcon: 'utensils',
  },
  {
    name: 'Macro Master',
    description: 'Hit your macro targets 7 days in a row',
    category: 'nutrition',
    requirementType: 'macro_streak',
    requirementValue: 7,
    xpReward: 300,
    badgeIcon: 'pie-chart',
  },
  {
    name: 'Meal Prep Pro',
    description: 'Create 5 meal plans',
    category: 'nutrition',
    requirementType: 'meal_plans_created',
    requirementValue: 5,
    xpReward: 250,
    badgeIcon: 'clipboard-list',
  },
];

// Helper to get achievements by category
export function getAchievementsByCategory(category: AchievementDefinition['category']): AchievementDefinition[] {
  return ACHIEVEMENT_DEFINITIONS.filter(a => a.category === category);
}

// Helper to get visible achievements only
export function getVisibleAchievements(): AchievementDefinition[] {
  return ACHIEVEMENT_DEFINITIONS.filter(a => !a.isHidden);
}

// Achievement category metadata
export const ACHIEVEMENT_CATEGORIES = [
  { id: 'consistency', name: 'Consistency', description: 'Rewards for showing up regularly', icon: 'calendar' },
  { id: 'strength', name: 'Strength', description: 'Rewards for getting stronger', icon: 'dumbbell' },
  { id: 'volume', name: 'Volume', description: 'Rewards for total work done', icon: 'scale' },
  { id: 'exploration', name: 'Exploration', description: 'Rewards for trying new things', icon: 'compass' },
  { id: 'social', name: 'Social', description: 'Rewards for coaching and community', icon: 'users' },
  { id: 'nutrition', name: 'Nutrition', description: 'Rewards for tracking nutrition', icon: 'utensils' },
] as const;
